### PR TITLE
Test with complex numbers and complex ffts

### PR DESCRIPTION
**Pull request by matteobachetti**

### CODE REVIEW

**Comment by fasiha** [comment]
Will the test work for fully-complex inputs (where imaginary component is different from zero)?

**Comment by matteobachetti** [comment]
Right. I was worried about the failure with complex numbers and just tried the same input with a different data type. However, if I use 
```
  x = np.random.randint(-30, 30, size=(nx, nx)) + np.random.randint(-30, 30, size=(nx, nx)) *1j
  h = np.random.randint(-20, 20, size=(nh, nh)) + np.random.randint(-20, 20, size=(nh, nh)) * 1j
```
The test fails again. So there must be something else going wrong there...

**Comment by fasiha** [comment]
No worries, I'm missing an extra `np.conj`, I should have a fix with full complex support shortly!

**Comment by matteobachetti** [comment]
Thanks! Also, thanks a lot for releasing this code to the public domain. I will use it in another piece of software (released with the BSD license), with an acknowledgement and a link to this page. Let me know if it is sufficient or you would like some other mention/reference. I haven't found a CITATION guideline or similar :).

**Comment by fasiha** [comment]
Yay, published 1.1.1 to PyPI, please check it out 🥳!

I hope I didn't break anything 😅…

> Let me know if it is sufficient or you would like some other mention/reference

This isn't just sufficient, it's more than sufficient 🙏. No CITATION, I'm an independent programmer, and signal processing is just my side hobby.

**Comment by matteobachetti** [comment]
@fasiha: In order to limit the dependencies, I would like to include the python source (+ array_range and nextprod) as part of the software I distribute, with *proper acknowledgement*. This is why I asked :). The unlicense allows it, but I still like to make sure that the work of different people is properly recognized.

**Comment by fasiha** [comment]
Thank you for taking attribution and licenses so seriously, as both a user and as an open source author I truly appreciate it!

**Pull request merged**
